enableColors: true

nmHoistingLimits: workspaces

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

# Fix for Vercel deployment issues
enableGlobalCache: true
pnpEnableEsmLoader: true
pnpMode: loose

# Ignore specific problematic peer dependencies
packageExtensions:
  "@nomicfoundation/hardhat-toolbox@*":
    peerDependencies:
      "@types/mocha": "*"
      "@types/node": "*"
      "typescript": "*"
      "typechain": "*"
      "hardhat": "*"
  "hardhat-gas-reporter@*":
    peerDependencies:
      "hardhat": "*"
  "@typechain/hardhat@*":
    peerDependencies:
      "hardhat": "*"
      "typechain": "*"
  "@nomicfoundation/hardhat-chai-matchers@*":
    peerDependencies:
      "hardhat": "*"
      "chai": ">=4.2.0"
  "@nomicfoundation/hardhat-ethers@*":
    peerDependencies:
      "hardhat": "*"
  "@nomicfoundation/hardhat-network-helpers@*":
    peerDependencies:
      "hardhat": "*"
  "@nomicfoundation/hardhat-verify@*":
    peerDependencies:
      "hardhat": "*"
  "solidity-coverage@*":
    peerDependencies:
      "hardhat": "*"
  "ts-node@*":
    peerDependencies:
      "@types/node": "*"
      "typescript": "*"
  "@typechain/ethers-v6@*":
    peerDependencies:
      "typechain": "*"
      "typescript": "*"
