/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    // ... existing code ...
  },
  21000001: {
    CropToken: {
      address: "0xdcD05f8a029F0A7998fDF29f0e9AE6a97541e370",
      abi: [
        
      ],
      inheritedFunctions: {},
    },
    CropCircle: {
      address: "0x8b9Fa5293f2Bec34bB5eE382eb291eAfE81AF85b",
      abi: [
        
      ],
      inheritedFunctions: {},
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration; 